using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml;
using System.Xml.Linq;
using TestvaerkstedetToolkit.Models;

namespace TestvaerkstedetToolkit.Services
{
    /// <summary>
    /// Service for primary key analysis and validation
    /// Analyserer primærnøgle unikhed for composite og single PK
    /// </summary>
    public class PrimaryKeyAnalysisService
    {
        /// <summary>
        /// Analysér combined unikhed for composite eller single PK
        /// </summary>
        public AnalysisResult AnalyzeCompositePrimaryKeyUniqueness(
            string xmlPath,
            List<string> pkColumnNames,
            TableIndexEntry tableEntry,
            PrimaryKeyInfo pkInfo)
        {
            var uniqueValues = new HashSet<string>();
            int totalCount = 0;
            int nullCount = 0;

            // Pre-build columnID lookup
            var columnIDMap = new Dictionary<string, string>();
            var columnNullableMap = new Dictionary<string, bool>();

            System.Diagnostics.Debug.WriteLine("=== PK ANALYSE START ===");
            System.Diagnostics.Debug.WriteLine($"Analyserer PK kolonner: {string.Join(", ", pkColumnNames)}");

            foreach (var pkColumnName in pkColumnNames)
            {
                if (pkColumnName == pkInfo.AutoGeneratedColumnName && pkInfo.IncludeAutoGenerated)
                {
                    System.Diagnostics.Debug.WriteLine($"Skipper auto-generated: {pkColumnName}");
                    continue;
                }

                var tableColumn = tableEntry?.Columns?.FirstOrDefault(c => c.Name == pkColumnName);
                if (tableColumn != null)
                {
                    columnIDMap[pkColumnName] = tableColumn.ColumnID;
                    columnNullableMap[pkColumnName] = tableColumn.IsNullable;
                    System.Diagnostics.Debug.WriteLine($"Mapped: '{pkColumnName}' → '{tableColumn.ColumnID}', nullable={tableColumn.IsNullable}");
                }
            }

            using (var reader = XmlReader.Create(xmlPath, new XmlReaderSettings
            {
                IgnoreWhitespace = true,
                IgnoreComments = true
            }))
            {
                while (reader.Read())
                {
                    if (reader.NodeType == XmlNodeType.Element && reader.Name == "row")
                    {
                        totalCount++;
                        bool debugThisRow = totalCount <= 3;

                        if (debugThisRow)
                        {
                            System.Diagnostics.Debug.WriteLine($"\n--- ROW {totalCount} ---");
                        }

                        // KORREKT APPROACH: Læs row som string først, parse bagefter
                        string rowXml = reader.ReadOuterXml();

                        // Parse med XDocument for SIKKER kolonnetilgang
                        var rowDoc = XDocument.Parse(rowXml);
                        var ns = rowDoc.Root.GetDefaultNamespace();

                        if (debugThisRow)
                        {
                            var allColumns = rowDoc.Descendants().Where(e => e.Name.LocalName.StartsWith("c")).Select(e => e.Name.LocalName);
                            System.Diagnostics.Debug.WriteLine($"  Kolonner i row: {string.Join(", ", allColumns)}");
                        }

                        // Byg sammensatte PK
                        var keyParts = new List<string>();
                        bool hasNull = false;
                        string nullReason = "";

                        foreach (var pkColumnName in pkColumnNames)
                        {
                            if (pkColumnName == pkInfo.AutoGeneratedColumnName && pkInfo.IncludeAutoGenerated)
                                continue;

                            if (!columnIDMap.ContainsKey(pkColumnName))
                            {
                                hasNull = true;
                                nullReason = $"Kolonne '{pkColumnName}' ikke i mapping";
                                break;
                            }

                            string columnID = columnIDMap[pkColumnName];
                            bool isNullable = columnNullableMap[pkColumnName];

                            var valueElement = rowDoc.Descendants(ns + columnID).FirstOrDefault();

                            if (debugThisRow)
                            {
                                System.Diagnostics.Debug.WriteLine($"  Søger efter: {columnID} ('{pkColumnName}')");
                            }

                            if (valueElement == null)
                            {
                                // Kolonne mangler i XML
                                if (isNullable)
                                {
                                    hasNull = true;
                                    nullReason = $"Nullable kolonne '{columnID}' mangler i XML";
                                    if (debugThisRow)
                                    {
                                        System.Diagnostics.Debug.WriteLine($"    → Ikke fundet (nullable)");
                                    }
                                    break;
                                }
                                else
                                {
                                    // NOT NULL kolonne mangler - kritisk!
                                    hasNull = true;
                                    nullReason = $"KRITISK: Not-null kolonne '{columnID}' mangler i XML";
                                    if (debugThisRow)
                                    {
                                        System.Diagnostics.Debug.WriteLine($"    → Ikke fundet (NOT NULL - FEJL!)");
                                    }
                                    break;
                                }
                            }

                            // Tjek for explicit null
                            var nilAttr = valueElement.Attribute(XNamespace.Get("http://www.w3.org/2001/XMLSchema-instance") + "nil");
                            bool isExplicitNull = nilAttr?.Value?.ToLower() == "true";
                            string value = valueElement.Value;
                            bool isEmpty = string.IsNullOrWhiteSpace(value);

                            if (debugThisRow)
                            {
                                System.Diagnostics.Debug.WriteLine($"    → Værdi: '{value}' (xsi:nil={isExplicitNull}, empty={isEmpty})");
                            }

                            if (isExplicitNull)
                            {
                                hasNull = true;
                                nullReason = $"Kolonne '{columnID}' har xsi:nil='true'";
                                break;
                            }
                            else if (isEmpty)
                            {
                                if (isNullable)
                                {
                                    hasNull = true;
                                    nullReason = $"Kolonne '{columnID}' er tom (nullable)";
                                    break;
                                }
                                else
                                {
                                    // Tom streng i NOT NULL kolonne = valid værdi
                                    keyParts.Add("");
                                }
                            }
                            else
                            {
                                keyParts.Add(value.Trim());
                            }
                        }

                        if (hasNull)
                        {
                            nullCount++;
                            if (nullCount <= 5 || debugThisRow)
                            {
                                System.Diagnostics.Debug.WriteLine($"  RESULTAT: NULL ({nullReason})");
                            }
                        }
                        else
                        {
                            string compositeKey = string.Join("|", keyParts);
                            uniqueValues.Add(compositeKey);

                            if (debugThisRow)
                            {
                                System.Diagnostics.Debug.WriteLine($"  RESULTAT: Key = '{compositeKey}'");
                            }
                        }

                        // GC hint hver 10000 rows
                        if (totalCount % 10000 == 0)
                        {
                            System.Diagnostics.Debug.WriteLine($"Processed {totalCount:N0} rows, {uniqueValues.Count:N0} unique, {nullCount:N0} null");
                        }
                    }
                }
            }

            System.Diagnostics.Debug.WriteLine($"\n=== PK ANALYSE SLUT ===");
            System.Diagnostics.Debug.WriteLine($"Total: {totalCount:N0}, Unique: {uniqueValues.Count:N0}, Null: {nullCount:N0}");

            return new AnalysisResult
            {
                UniqueCount = uniqueValues.Count,
                TotalCount = totalCount,
                NullCount = nullCount
            };
        }

        /// <summary>
        /// Byg PK analyse besked
        /// </summary>
        public string BuildPKAnalysisMessage(List<string> pkColumns, int uniqueCount, int totalCount, int nullCount)
        {
            string pkDescription = pkColumns.Count == 1 ?
                $"kolonne '{pkColumns[0]}'" :
                $"kombinerede kolonner: {string.Join(", ", pkColumns)}";

            string message = $"Analyse af primærnøgle {pkDescription}:\n\n" +
                           $"• Total rækker: {totalCount:N0}\n" +
                           $"• Unikke kombinationer: {uniqueCount:N0}\n" +
                           $"• Rækker med null/tomme værdier: {nullCount:N0}\n\n";

            return message;
        }
    }
}