using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Xml;
using System.Xml.Linq;
using TestvaerkstedetToolkit.Models;

namespace TestvaerkstedetToolkit.Services
{
    /// <summary>
    /// Service for generation of XML files for split tables
    /// Håndterer skrivning af XML filer med korrekt kolonne placering og composite PK support
    /// </summary>
    public class XMLFileGenerationService
    {
        /// <summary>
        /// Generer XML og XSD filer for split tabel med sammensat PK support
        /// </summary>
        public void GenerateTableFiles(SplitTable table, string outputDirectory, UIDataContainer uiData, int tableNumber)
        {
            // Direkte table folder uden beskrivende wrapper
            string tableFolder = $"table{tableNumber}";
            string tablePath = Path.Combine(outputDirectory, tableFolder);
            Directory.CreateDirectory(tablePath);

            // XML fil med korrekt navn og namespace
            string xmlFileName = $"table{tableNumber}.xml";
            string xmlPath = Path.Combine(tablePath, xmlFileName);

            // Generer namespace med korrekt tabelnummer
            string newNamespace = $"http://www.sa.dk/xmlns/siard/1.0/schema0/table{tableNumber}.xsd";

            GenerateXMLFile(table, xmlPath, newNamespace, uiData, tableNumber);
        }

        /// <summary>
        /// Generer XML fil for split tabel med sammensat PK support
        /// </summary>
        private void GenerateXMLFile(SplitTable table, string xmlPath, string newNamespace, UIDataContainer uiData, int tableNumber)
        {
            string xsdFileName = $"table{tableNumber}.xsd";

            using (var writer = XmlWriter.Create(xmlPath, new XmlWriterSettings
            {
                Indent = true,
                IndentChars = "  ",
                Encoding = Encoding.UTF8
            }))
            {
                writer.WriteStartDocument();
                writer.WriteStartElement("table", newNamespace);
                writer.WriteAttributeString("xmlns", "xsi", null, "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteAttributeString("xsi", "schemaLocation", "http://www.w3.org/2001/XMLSchema-instance", $"{newNamespace} {xsdFileName}");

                ProcessXMLRowsWithCompositePK(writer, table, uiData);

                writer.WriteEndElement();
                writer.WriteEndDocument();
            }
        }

        /// <summary>
        /// Process XML rækker med sammensat PK support og korrekt kolonne placering
        /// </summary>
        private void ProcessXMLRowsWithCompositePK(XmlWriter writer, SplitTable table, UIDataContainer uiData)
        {
            int currentRowId = 1;
            var pkInfo = uiData.PrimaryKey;
            var pkColumns = pkInfo.GetAllPrimaryKeyColumns();

            using (var reader = XmlReader.Create(uiData.XMLPath))
            {
                while (reader.Read())
                {
                    if (reader.NodeType == XmlNodeType.Element && reader.Name == "row")
                    {
                        var rowXml = reader.ReadOuterXml();
                        var rowDoc = XDocument.Parse(rowXml);
                        var ns = rowDoc.Root.GetDefaultNamespace();

                        writer.WriteStartElement("row");
                        int xmlColumnCounter = 1;

                        if (table.SplitIndex == 1)
                        {
                            // TABLE 1: Behold original struktur med PK på original position
                            foreach (var column in table.Columns.OrderBy(c => c.Position))
                            {
                                // Skip auto-generated kolonne - den håndteres efter loopen
                                if (column.Name == pkInfo.AutoGeneratedColumnName && pkInfo.IncludeAutoGenerated)
                                {
                                    continue;
                                }

                                if (pkColumns.Contains(column.Name))
                                {
                                    // Eksisterende PK kolonne - kopier fra original XML
                                    WriteExistingPKColumn(writer, xmlColumnCounter, column, rowDoc, ns, uiData);
                                }
                                else
                                {
                                    // Data kolonne
                                    WriteDataColumn(writer, xmlColumnCounter, column, rowDoc, ns);
                                }
                                xmlColumnCounter++;
                            }

                            // Auto-generated PK i slutningen - KUN ÉN GANG
                            if (pkInfo.IncludeAutoGenerated)
                            {
                                WriteAutoGeneratedPKColumn(writer, xmlColumnCounter, currentRowId);
                                xmlColumnCounter++;
                            }
                        }
                        else
                        {
                            // TABLE 2+: Data kolonner først, PK kolonner i slutningen
                            var dataColumns = table.Columns
                                .Where(c => !pkColumns.Contains(c.Name))
                                .OrderBy(c => c.Position);

                            // Filtrer auto-generated kolonne fra eksisterende PK kolonner
                            var pkColumnsInTable = table.Columns
                                .Where(c => pkColumns.Contains(c.Name) &&
                                            c.Name != pkInfo.AutoGeneratedColumnName)
                                .OrderBy(c => c.Position);

                            // Skriv data kolonner først
                            foreach (var column in dataColumns)
                            {
                                WriteDataColumn(writer, xmlColumnCounter, column, rowDoc, ns);
                                xmlColumnCounter++;
                            }

                            // Skriv eksisterende PK kolonner
                            foreach (var column in pkColumnsInTable)
                            {
                                WriteExistingPKColumn(writer, xmlColumnCounter, column, rowDoc, ns, uiData);
                                xmlColumnCounter++;
                            }

                            // Auto-generated PK kolonne allersidst - KUN ÉN GANG
                            if (pkInfo.IncludeAutoGenerated)
                            {
                                WriteAutoGeneratedPKColumn(writer, xmlColumnCounter, currentRowId);
                                xmlColumnCounter++;
                            }
                        }

                        writer.WriteEndElement(); // </row>
                        currentRowId++;
                    }
                }
            }
        }

        /// <summary>
        /// Skriv eksisterende PK kolonne
        /// </summary>
        private void WriteExistingPKColumn(XmlWriter writer, int columnNumber, XMLColumn column, XDocument rowDoc, XNamespace ns, UIDataContainer uiData)
        {
            writer.WriteStartElement($"c{columnNumber}");

            var element = rowDoc.Descendants(ns + column.ColumnID).FirstOrDefault();

            if (element != null)
            {
                var xsiNs = XNamespace.Get("http://www.w3.org/2001/XMLSchema-instance");
                var nilAttr = element.Attribute(xsiNs + "nil");

                bool hasNilAttribute = nilAttr?.Value?.ToLower() == "true";
                bool hasValue = !string.IsNullOrWhiteSpace(element.Value);

                if (hasNilAttribute)
                {
                    writer.WriteAttributeString("xsi", "nil", xsiNs.NamespaceName, "true");
                }
                else if (hasValue)
                {
                    writer.WriteString(element.Value);
                }
                else
                {
                    if (column.IsNullable)
                    {
                        writer.WriteAttributeString("xsi", "nil", xsiNs.NamespaceName, "true");
                    }
                    else
                    {
                        // Not-null PK med tom værdi - LOG kun dette
                        System.Diagnostics.Debug.WriteLine($"WARNING: Not-null PK {column.ColumnID} has empty value");
                    }
                }
            }
            else
            {
                // PK kolonne mangler HELT - DET er kritisk!
                System.Diagnostics.Debug.WriteLine($"CRITICAL: PK column {column.ColumnID} missing in source XML!");

                if (column.IsNullable)
                {
                    writer.WriteAttributeString("xsi", "nil", "http://www.w3.org/2001/XMLSchema-instance", "true");
                }
            }

            writer.WriteEndElement();
        }

        /// <summary>
        /// Skriv data kolonne
        /// </summary>
        private void WriteDataColumn(XmlWriter writer, int columnNumber, XMLColumn column, XDocument rowDoc, XNamespace ns)
        {
            writer.WriteStartElement($"c{columnNumber}");

            var element = rowDoc.Descendants(ns + column.ColumnID).FirstOrDefault();

            if (element != null)
            {
                var xsiNs = XNamespace.Get("http://www.w3.org/2001/XMLSchema-instance");
                var nilAttr = element.Attribute(xsiNs + "nil");

                bool hasNilAttribute = nilAttr?.Value?.ToLower() == "true";
                bool hasValue = !string.IsNullOrWhiteSpace(element.Value);

                if (hasNilAttribute)
                {
                    writer.WriteAttributeString("xsi", "nil", xsiNs.NamespaceName, "true");
                }
                else if (hasValue)
                {
                    writer.WriteString(element.Value);
                }
                else
                {
                    if (column.IsNullable)
                    {
                        writer.WriteAttributeString("xsi", "nil", xsiNs.NamespaceName, "true");
                    }
                }
            }
            else
            {
                // SPARSE XML: Kolonne mangler i source = null værdi (NORMALT)
                if (column.IsNullable)
                {
                    writer.WriteAttributeString("xsi", "nil", "http://www.w3.org/2001/XMLSchema-instance", "true");
                }
                // For not-null kolonner: skriv tomt element (XSD validering håndterer det)
            }

            writer.WriteEndElement();
        }

        /// <summary>
        /// Skriv auto-generated PK kolonne
        /// </summary>
        private void WriteAutoGeneratedPKColumn(XmlWriter writer, int columnNumber, int rowId)
        {
            writer.WriteStartElement($"c{columnNumber}");
            writer.WriteString(rowId.ToString());
            writer.WriteEndElement();
        }
    }
}