namespace TestvaerkstedetToolkit.Controls
{
    partial class CompositePKSelector
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.SuspendLayout();

            // Setup main container
            this.Size = new System.Drawing.Size(720, 320);
            this.BackColor = System.Drawing.SystemColors.Control;

            // Existing columns label
            this.lblExistingColumns = new System.Windows.Forms.Label();
            this.lblExistingColumns.Text = "Vælg eksisterende kolonner til primærnøgle:";
            this.lblExistingColumns.Location = new System.Drawing.Point(10, 10);
            this.lblExistingColumns.Size = new System.Drawing.Size(700, 25);
            this.lblExistingColumns.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold);
            this.Controls.Add(this.lblExistingColumns);

            // Existing columns checkedlistbox
            this.clbExistingColumns = new System.Windows.Forms.CheckedListBox();
            this.clbExistingColumns.Location = new System.Drawing.Point(10, 35);
            this.clbExistingColumns.Size = new System.Drawing.Size(450, 120);
            this.clbExistingColumns.CheckOnClick = true;
            this.clbExistingColumns.SelectionMode = System.Windows.Forms.SelectionMode.One;
            this.clbExistingColumns.IntegralHeight = false;
            this.clbExistingColumns.Font = new System.Drawing.Font("Courier New", 8.25F);
            this.clbExistingColumns.ItemCheck += new System.Windows.Forms.ItemCheckEventHandler(this.ClbExistingColumns_ItemCheck);
            this.Controls.Add(this.clbExistingColumns);

            // Auto-generated checkbox
            this.chkIncludeAutoGenerated = new System.Windows.Forms.CheckBox();
            this.chkIncludeAutoGenerated.Text = "Tilføj auto-genereret kolonne\ntil primærnøgle";
            this.chkIncludeAutoGenerated.Location = new System.Drawing.Point(480, 35);
            this.chkIncludeAutoGenerated.Size = new System.Drawing.Size(230, 50);
            this.chkIncludeAutoGenerated.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold);
            this.chkIncludeAutoGenerated.CheckedChanged += new System.EventHandler(this.ChkIncludeAutoGenerated_CheckedChanged);
            this.Controls.Add(this.chkIncludeAutoGenerated);

            // Auto-generated name textbox
            this.txtAutoGeneratedName = new System.Windows.Forms.TextBox();
            this.txtAutoGeneratedName.Text = "AutoID";
            this.txtAutoGeneratedName.Location = new System.Drawing.Point(480, 95);
            this.txtAutoGeneratedName.Size = new System.Drawing.Size(150, 23);
            this.txtAutoGeneratedName.Enabled = false;
            this.txtAutoGeneratedName.TextChanged += new System.EventHandler(this.TxtAutoGeneratedName_TextChanged);
            this.Controls.Add(this.txtAutoGeneratedName);

            // Preview label
            this.lblPreview = new System.Windows.Forms.Label();
            this.lblPreview.Text = "Primærnøgle preview:";
            this.lblPreview.Location = new System.Drawing.Point(10, 170);
            this.lblPreview.Size = new System.Drawing.Size(150, 20);
            this.lblPreview.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold);
            this.Controls.Add(this.lblPreview);

            // Preview value
            this.lblPreviewValue = new System.Windows.Forms.Label();
            this.lblPreviewValue.Text = "Ingen primærnøgle valgt";
            this.lblPreviewValue.Location = new System.Drawing.Point(170, 170);
            this.lblPreviewValue.Size = new System.Drawing.Size(540, 35);
            this.lblPreviewValue.ForeColor = System.Drawing.Color.DarkRed;
            this.lblPreviewValue.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular);
            this.Controls.Add(this.lblPreviewValue);

            // Capacity info label
            this.lblCapacityInfo = new System.Windows.Forms.Label();
            this.lblCapacityInfo.Text = "Tilgængelig plads per split:";
            this.lblCapacityInfo.Location = new System.Drawing.Point(10, 200);
            this.lblCapacityInfo.AutoSize = true;
            this.lblCapacityInfo.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold);
            this.Controls.Add(this.lblCapacityInfo);

            // Capacity value
            this.lblCapacityValue = new System.Windows.Forms.Label();
            this.lblCapacityValue.Text = "Vælg primærnøgle for beregning";
            this.lblCapacityValue.Location = new System.Drawing.Point(280, 200);
            this.lblCapacityValue.Size = new System.Drawing.Size(430, 80);
            this.lblCapacityValue.ForeColor = System.Drawing.Color.DarkGreen;
            this.lblCapacityValue.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular);
            this.Controls.Add(this.lblCapacityValue);

            // Info text at bottom
            System.Windows.Forms.Label lblInfo = new System.Windows.Forms.Label();
            lblInfo.Text = "💡 Sammensat primærnøgle: Vælg flere kolonner for øget unikhed";
            lblInfo.Location = new System.Drawing.Point(10, 290);
            lblInfo.Size = new System.Drawing.Size(700, 20);
            lblInfo.ForeColor = System.Drawing.Color.DarkBlue;
            lblInfo.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Italic);
            this.Controls.Add(lblInfo);

            this.ResumeLayout(false);
        }
        private System.Windows.Forms.CheckedListBox clbExistingColumns;
        private System.Windows.Forms.CheckBox chkIncludeAutoGenerated;
        private System.Windows.Forms.TextBox txtAutoGeneratedName;
        private System.Windows.Forms.Label lblExistingColumns;
        private System.Windows.Forms.Label lblPreview;
        private System.Windows.Forms.Label lblCapacityInfo;
        private System.Windows.Forms.Label lblPreviewValue;
        private System.Windows.Forms.Label lblCapacityValue;
    }
}
