namespace TestvaerkstedetToolkit.Controls
{
    partial class CompositePKSelector
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.lblExistingColumns = new System.Windows.Forms.Label();
            this.clbExistingColumns = new System.Windows.Forms.CheckedListBox();
            this.chkIncludeAutoGenerated = new System.Windows.Forms.CheckBox();
            this.txtAutoGeneratedName = new System.Windows.Forms.TextBox();
            this.lblPreview = new System.Windows.Forms.Label();
            this.lblPreviewValue = new System.Windows.Forms.Label();
            this.lblCapacityInfo = new System.Windows.Forms.Label();
            this.lblCapacityValue = new System.Windows.Forms.Label();
            this.lblInfo = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // lblExistingColumns
            // 
            this.lblExistingColumns.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold);
            this.lblExistingColumns.Location = new System.Drawing.Point(10, 10);
            this.lblExistingColumns.Name = "lblExistingColumns";
            this.lblExistingColumns.Size = new System.Drawing.Size(700, 25);
            this.lblExistingColumns.TabIndex = 0;
            this.lblExistingColumns.Text = "Vælg eksisterende kolonner til primærnøgle:";
            // 
            // clbExistingColumns
            // 
            this.clbExistingColumns.CheckOnClick = true;
            this.clbExistingColumns.Font = new System.Drawing.Font("Courier New", 8.25F);
            this.clbExistingColumns.IntegralHeight = false;
            this.clbExistingColumns.Location = new System.Drawing.Point(10, 35);
            this.clbExistingColumns.Name = "clbExistingColumns";
            this.clbExistingColumns.Size = new System.Drawing.Size(450, 120);
            this.clbExistingColumns.TabIndex = 1;
            this.clbExistingColumns.ItemCheck += new System.Windows.Forms.ItemCheckEventHandler(this.ClbExistingColumns_ItemCheck);
            // 
            // chkIncludeAutoGenerated
            // 
            this.chkIncludeAutoGenerated.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold);
            this.chkIncludeAutoGenerated.Location = new System.Drawing.Point(480, 35);
            this.chkIncludeAutoGenerated.Name = "chkIncludeAutoGenerated";
            this.chkIncludeAutoGenerated.Size = new System.Drawing.Size(230, 50);
            this.chkIncludeAutoGenerated.TabIndex = 2;
            this.chkIncludeAutoGenerated.Text = "Tilføj auto-genereret kolonne\ntil primærnøgle";
            this.chkIncludeAutoGenerated.CheckedChanged += new System.EventHandler(this.ChkIncludeAutoGenerated_CheckedChanged);
            // 
            // txtAutoGeneratedName
            // 
            this.txtAutoGeneratedName.Enabled = false;
            this.txtAutoGeneratedName.Location = new System.Drawing.Point(480, 95);
            this.txtAutoGeneratedName.Name = "txtAutoGeneratedName";
            this.txtAutoGeneratedName.Size = new System.Drawing.Size(150, 20);
            this.txtAutoGeneratedName.TabIndex = 3;
            this.txtAutoGeneratedName.Text = "AutoID";
            this.txtAutoGeneratedName.TextChanged += new System.EventHandler(this.TxtAutoGeneratedName_TextChanged);
            // 
            // lblPreview
            // 
            this.lblPreview.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold);
            this.lblPreview.Location = new System.Drawing.Point(10, 170);
            this.lblPreview.Name = "lblPreview";
            this.lblPreview.Size = new System.Drawing.Size(150, 20);
            this.lblPreview.TabIndex = 4;
            this.lblPreview.Text = "Primærnøgle preview:";
            // 
            // lblPreviewValue
            // 
            this.lblPreviewValue.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.lblPreviewValue.ForeColor = System.Drawing.Color.DarkRed;
            this.lblPreviewValue.Location = new System.Drawing.Point(170, 170);
            this.lblPreviewValue.Name = "lblPreviewValue";
            this.lblPreviewValue.Size = new System.Drawing.Size(540, 35);
            this.lblPreviewValue.TabIndex = 5;
            this.lblPreviewValue.Text = "Ingen primærnøgle valgt";
            // 
            // lblCapacityInfo
            // 
            this.lblCapacityInfo.AutoSize = true;
            this.lblCapacityInfo.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold);
            this.lblCapacityInfo.Location = new System.Drawing.Point(10, 205);
            this.lblCapacityInfo.Name = "lblCapacityInfo";
            this.lblCapacityInfo.Size = new System.Drawing.Size(182, 15);
            this.lblCapacityInfo.TabIndex = 6;
            this.lblCapacityInfo.Text = "Tilgængelig plads per split:";
            // 
            // lblCapacityValue
            // 
            this.lblCapacityValue.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.lblCapacityValue.ForeColor = System.Drawing.Color.DarkGreen;
            this.lblCapacityValue.Location = new System.Drawing.Point(280, 205);
            this.lblCapacityValue.Name = "lblCapacityValue";
            this.lblCapacityValue.Size = new System.Drawing.Size(430, 75);
            this.lblCapacityValue.TabIndex = 7;
            this.lblCapacityValue.Text = "Vælg primærnøgle for beregning";
            // 
            // lblInfo
            // 
            this.lblInfo.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Italic);
            this.lblInfo.ForeColor = System.Drawing.Color.DarkBlue;
            this.lblInfo.Location = new System.Drawing.Point(10, 290);
            this.lblInfo.Name = "lblInfo";
            this.lblInfo.Size = new System.Drawing.Size(700, 20);
            this.lblInfo.TabIndex = 8;
            this.lblInfo.Text = "💡 Sammensat primærnøgle: Vælg flere kolonner for øget unikhed";
            // 
            // CompositePKSelector
            // 
            this.BackColor = System.Drawing.SystemColors.Control;
            this.Controls.Add(this.lblExistingColumns);
            this.Controls.Add(this.clbExistingColumns);
            this.Controls.Add(this.chkIncludeAutoGenerated);
            this.Controls.Add(this.txtAutoGeneratedName);
            this.Controls.Add(this.lblPreview);
            this.Controls.Add(this.lblPreviewValue);
            this.Controls.Add(this.lblCapacityInfo);
            this.Controls.Add(this.lblCapacityValue);
            this.Controls.Add(this.lblInfo);
            this.Name = "CompositePKSelector";
            this.Size = new System.Drawing.Size(720, 320);
            this.ResumeLayout(false);
            this.PerformLayout();

        }
        private System.Windows.Forms.CheckedListBox clbExistingColumns;
        private System.Windows.Forms.CheckBox chkIncludeAutoGenerated;
        private System.Windows.Forms.TextBox txtAutoGeneratedName;
        private System.Windows.Forms.Label lblExistingColumns;
        private System.Windows.Forms.Label lblPreview;
        private System.Windows.Forms.Label lblCapacityInfo;
        private System.Windows.Forms.Label lblPreviewValue;
        private System.Windows.Forms.Label lblCapacityValue;
        private System.Windows.Forms.Label lblInfo;
    }
}
